image:
  file: .gitpod.Dockerfile

ports:
  # frontend
  - port: 3002
    onOpen: open-preview
  # backend
  - port: 5001
    onOpen: ignore
  # PostgreSQL
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      yarn install &&
      cd apps/backend &&
      yarn prisma:init
    env:
      DATABASE_URL: "postgresql://gitpod@localhost"
      JWT_SECRET: "jwt_secret"
      FRONTEND_ORIGIN: "http://localhost:3002"
      NODE_ENV: "development"
      NEXT_PUBLIC_INSTAGRAM_CLONE_API_URL: "http://localhost:5001/graphql"
    command: yarn dev
