services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ..:/workspace:cached
      - extensions:/root/.vscode-server/extensions
      - frontend-node_modules:/workspace/apps/frontend/node_modules
      - backend-node_modules:/workspace/apps/backend/node_modules
      - common-node_modules:/workspace/node_modules
      - ~/.ssh:/root/.ssh
    command: sleep infinity
    network_mode: host

  db-dev:
    container_name: "db_dev"
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  # db-test:
  #   container_name: "db_test"
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5433:5432

volumes:
  postgres-data:
  common-node_modules:
  frontend-node_modules:
  backend-node_modules:
  extensions:
