name: CI

on:
  push:
    branches:
      - main

jobs:
  Line-Notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Send line notification
        uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_NOTIFY_TOKEN }}
          message: "\n\n⚠️⚠️⚠️Github Actionが失敗しました⚠️⚠️⚠️\n\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
