name: CI

on:
  push:
    branches:
      - main

jobs:
  Cancel-Previous-Runs:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  Detect-Changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      cypress: ${{ steps.filter.outputs.cypress }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Filter paths changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'apps/backend/**'
            frontend:
              - 'apps/frontend/**'
            cypress:
              - 'cypress/**'

  Build-Backend:
    if: needs.Detect-Changes.outputs.backend == 'true'
    needs: [Detect-Changes, Cancel-Previous-Runs]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  Build-Frontend:
    if: needs.Detect-Changes.outputs.frontend == 'true' && !failure()
    needs: [Build-Backend]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}

  Analyze-Frontend-Bundle:
    if: needs.Detect-Changes.outputs.frontend == 'true' && !failure()
    needs: [Build-Backend]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: node_modules_cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Seed database
        run: yarn prisma:init
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
        working-directory: apps/backend

      - name: Start backend
        run: yarn dev &
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public
          NODE_ENV: development
          JWT_SECRET: jwt_secret
          FRONTEND_ORIGIN: http://localhost:3002
        working-directory: apps/backend

      - name: Build for bundle analyzing
        run: yarn next build
        working-directory: apps/frontend
        env:
          NEXT_PUBLIC_INSTAGRAM_CLONE_API_URL: http://localhost:5001/graphql
          NODE_ENV: production
          ANALYZE: true

      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report
        working-directory: apps/frontend

      - name: Upload bundle analysis report for future comparison
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: apps/frontend/dist/analyze/__bundle_analysis.json

      - name: Upload bundle analysis report Report
        uses: actions/upload-artifact@v3
        with:
          name: Bundle Analysis Report
          path: apps/frontend/dist/analyze/client.html

      - name: Check previous bundle analysis exsistance
        uses: dawidd6/action-download-artifact@v2
        id: download_artifact
        if: success()
        continue-on-error: true
        with:
          workflow: ci.yml
          name: bundle
          dry_run: true

      - name: Download previous bundle analysis report
        uses: dawidd6/action-download-artifact@v2
        if: success() && steps.download_artifact.outputs.dry_run == 'true'
        with:
          workflow: ci.yml
          path: apps/frontend/dist/analyze/base
          name: bundle

      - name: Compare with previous bundle analysis report
        if: success() && steps.download_artifact.outputs.dry_run == 'true'
        run: npx -p nextjs-bundle-analysis compare
        working-directory: apps/frontend

      - name: Print Result
        if: success() && steps.download_artifact.outputs.dry_run == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const output = fs.readFileSync("apps/frontend/dist/analyze/__bundle_analysis_comment.txt");
            await core.summary
              .addRaw(output)
              .write()

  Purge-Cloudflare-Cache:
    if: always() && needs.Build-Frontend.result == 'success'
    needs: [Build-Frontend]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Wait 30 seconds to purge cloudflare cache
        run: sleep 30s
        shell: bash

  E2E-Test:
    if: always() && (needs.Detect-Changes.outputs.backend == 'true' || needs.Detect-Changes.outputs.frontend == 'true' || needs.Detect-Changes.outputs.cypress == 'true')
    needs: [Purge-Cloudflare-Cache]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Japanese font
        run: sudo apt-get install fonts-noto -y

      - name: Test On Chrome
        uses: cypress-io/github-action@v4
        with:
          browser: chrome

      - name: Upload Test Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress Videos
          path: cypress/videos

      - name: Upload Test Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress Screenshots
          path: cypress/screenshots
